apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: loki
  namespace: observability
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    higress.io/domain: "loki.nhome.local"
spec:
  ingressClassName: higress
  rules:
    - host: loki.nhome.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: loki
                port:
                  number: 3100
