apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docs-rs-mcp
  namespace: argocd
  labels:
    app: docs-rs-mcp
spec:
  project: default
  source:
    repoURL: https://github.com/BestNathan/nitops.git
    targetRevision: main
    path: components/mcp/docs-rs-mcp
  destination:
    server: https://kubernetes.default.svc
    namespace: mcp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
