apiVersion: v1
kind: Service
metadata:
  name: higress-console
  namespace: higress-system
  labels:
    app: higress-console
spec:
  type: NodePort
  selector:
    app: higress-console
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31287
    name: http
    protocol: TCP
