apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  labels:
    app: grafana
spec:
  project: default
  source:
    repoURL: REPO_URL_PLACEHOLDER
    targetRevision: main
    path: components/observability/grafana
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
