apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
  labels:
    app: minio
    type: nfs
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 192.168.2.105
    path: "/mnt/share/minio"
